### ISSUE TITLE
Crash at runtime (optionsRowList)

### ISSUE THREAD

**Issue by Desempregago** [elytra/Vise#2]
• Vise version - 1.12.2-1.1
• Minecraft version - 1.12.2
• Forge version - 14.23.3.2669
• [Crash Report](https://gist.github.com/Fogrits/36e948b27da97b8563e59998d35ed60d)

**Comment by exaskye** [comment]
OptiFine is not supported.

**Comment by exaskye** [comment]
89a0467a
